/**
 * Static animated emoji catalog — 464 Noto Color Emoji animations.
 * Sourced from https://googlefonts.github.io/noto-emoji-animation/
 * CDN: fonts.gstatic.com/s/e/notoemoji/latest/{codepoint}/lottie.json
 *
 * This file is auto-generated. Do not edit manually.
 */

interface CatalogEntry {
  /** Hex codepoint (e.g. "1f600"). */
  c: string;
  /** Emoji character. */
  e: string;
  /** Human-readable name. */
  n: string;
}

/** CDN base URL for Noto animated emoji assets. */
export const NOTO_CDN = 'https://fonts.gstatic.com/s/e/notoemoji/latest';

/**
 * All animated Noto emojis with Lottie support.
 * Compact format: c=codepoint, e=emoji, n=name.
 */
export const ANIMATED_EMOJI_CATALOG: CatalogEntry[] = [
  { c: '1f304', e: '🌄', n: 'sunrise over mountains' },
  { c: '1f305', e: '🌅', n: 'sunrise' },
  { c: '1f308', e: '🌈', n: 'rainbow' },
  { c: '1f30a', e: '🌊', n: 'water wave' },
  { c: '1f30b', e: '🌋', n: 'volcano' },
  { c: '1f30d', e: '🌍', n: 'earth globe europe-africa' },
  { c: '1f30e', e: '🌎', n: 'earth globe americas' },
  { c: '1f30f', e: '🌏', n: 'earth globe asia-australia' },
  { c: '1f319', e: '🌙', n: 'crescent moon' },
  { c: '1f31b', e: '🌛', n: 'first quarter moon with face' },
  { c: '1f31c', e: '🌜', n: 'last quarter moon with face' },
  { c: '1f31e', e: '🌞', n: 'sun with face' },
  { c: '1f31f', e: '🌟', n: 'glowing star' },
  { c: '1f327', e: '🌧', n: 'cloud with rain' },
  { c: '1f329', e: '🌩', n: 'cloud with lightning' },
  { c: '1f32a', e: '🌪', n: 'cloud with tornado' },
  { c: '1f32c', e: '🌬', n: 'wind blowing face' },
  { c: '1f32e', e: '🌮', n: 'taco' },
  { c: '1f32f', e: '🌯', n: 'burrito' },
  { c: '1f331', e: '🌱', n: 'seedling' },
  { c: '1f338', e: '🌸', n: 'cherry blossom' },
  { c: '1f339', e: '🌹', n: 'rose' },
  { c: '1f33b', e: '🌻', n: 'sunflower' },
  { c: '1f340', e: '🍀', n: 'four leaf clover' },
  { c: '1f342', e: '🍂', n: 'fallen leaf' },
  { c: '1f343', e: '🍃', n: 'leaf fluttering in wind' },
  { c: '1f345', e: '🍅', n: 'tomato' },
  { c: '1f34e', e: '🍎', n: 'red apple' },
  { c: '1f354', e: '🍔', n: 'hamburger' },
  { c: '1f355', e: '🍕', n: 'pizza' },
  { c: '1f35c', e: '🍜', n: 'steaming bowl' },
  { c: '1f35d', e: '🍝', n: 'spaghetti' },
  { c: '1f35f', e: '🍟', n: 'french fries' },
  { c: '1f366', e: '🍦', n: 'soft ice cream' },
  { c: '1f373', e: '🍳', n: 'cooking' },
  { c: '1f377', e: '🍷', n: 'wine glass' },
  { c: '1f379', e: '🍹', n: 'tropical drink' },
  { c: '1f37a', e: '🍺', n: 'beer mug' },
  { c: '1f37b', e: '🍻', n: 'clinking beer mugs' },
  { c: '1f37e', e: '🍾', n: 'bottle with popping cork' },
  { c: '1f37f', e: '🍿', n: 'popcorn' },
  { c: '1f381', e: '🎁', n: 'wrapped present' },
  { c: '1f382', e: '🎂', n: 'birthday cake' },
  { c: '1f383', e: '🎃', n: 'jack-o-lantern' },
  { c: '1f386', e: '🎆', n: 'fireworks' },
  { c: '1f388', e: '🎈', n: 'balloon' },
  { c: '1f389', e: '🎉', n: 'party popper' },
  { c: '1f38a', e: '🎊', n: 'confetti ball' },
  { c: '1f393', e: '🎓', n: 'graduation cap' },
  { c: '1f3a1', e: '🎡', n: 'ferris wheel' },
  { c: '1f3a2', e: '🎢', n: 'roller coaster' },
  { c: '1f3a3', e: '🎣', n: 'fishing pole and fish' },
  { c: '1f3ac', e: '🎬', n: 'clapper board' },
  { c: '1f3ad', e: '🎭', n: 'performing arts' },
  { c: '1f3ae', e: '🎮', n: 'video game' },
  { c: '1f3af', e: '🎯', n: 'bullseye' },
  { c: '1f3b0', e: '🎰', n: 'slot machine' },
  { c: '1f3b1', e: '🎱', n: 'billiards' },
  { c: '1f3b2', e: '🎲', n: 'game die' },
  { c: '1f3b3', e: '🎳', n: 'bowling' },
  { c: '1f3b5', e: '🎵', n: 'musical note' },
  { c: '1f3b6', e: '🎶', n: 'musical notes' },
  { c: '1f3b7', e: '🎷', n: 'saxophone' },
  { c: '1f3ba', e: '🎺', n: 'trumpet' },
  { c: '1f3bb', e: '🎻', n: 'violin' },
  { c: '1f3be', e: '🎾', n: 'tennis racquet and ball' },
  { c: '1f3c0', e: '🏀', n: 'basketball' },
  { c: '1f3c1', e: '🏁', n: 'chequered flag' },
  { c: '1f3c6', e: '🏆', n: 'trophy' },
  { c: '1f3ce', e: '🏎', n: 'racing car' },
  { c: '1f3cf', e: '🏏', n: 'cricket bat and ball' },
  { c: '1f3d1', e: '🏑', n: 'field hockey stick and ball' },
  { c: '1f3d2', e: '🏒', n: 'ice hockey stick and puck' },
  { c: '1f3d3', e: '🏓', n: 'table tennis paddle and ball' },
  { c: '1f3d5', e: '🏕', n: 'camping' },
  { c: '1f3e0', e: '🏠', n: 'house' },
  { c: '1f3f3', e: '🏳', n: 'waving white flag' },
  { c: '1f3f4', e: '🏴', n: 'waving black flag' },
  { c: '1f3f8', e: '🏸', n: 'badminton racquet and shuttlecock' },
  { c: '1f400', e: '🐀', n: 'rat' },
  { c: '1f402', e: '🐂', n: 'ox' },
  { c: '1f405', e: '🐅', n: 'tiger' },
  { c: '1f407', e: '🐇', n: 'rabbit' },
  { c: '1f409', e: '🐉', n: 'dragon' },
  { c: '1f40a', e: '🐊', n: 'crocodile' },
  { c: '1f40c', e: '🐌', n: 'snail' },
  { c: '1f40d', e: '🐍', n: 'snake' },
  { c: '1f40e', e: '🐎', n: 'horse' },
  { c: '1f410', e: '🐐', n: 'goat' },
  { c: '1f412', e: '🐒', n: 'monkey' },
  { c: '1f413', e: '🐓', n: 'rooster' },
  { c: '1f415', e: '🐕', n: 'dog' },
  { c: '1f416', e: '🐖', n: 'pig' },
  { c: '1f419', e: '🐙', n: 'octopus' },
  { c: '1f41b', e: '🐛', n: 'bug' },
  { c: '1f41c', e: '🐜', n: 'ant' },
  { c: '1f41d', e: '🐝', n: 'honeybee' },
  { c: '1f41e', e: '🐞', n: 'lady beetle' },
  { c: '1f41f', e: '🐟', n: 'fish' },
  { c: '1f421', e: '🐡', n: 'blowfish' },
  { c: '1f422', e: '🐢', n: 'turtle' },
  { c: '1f423', e: '🐣', n: 'hatching chick' },
  { c: '1f424', e: '🐤', n: 'baby chick' },
  { c: '1f425', e: '🐥', n: 'front-facing baby chick' },
  { c: '1f426', e: '🐦', n: 'bird' },
  { c: '1f429', e: '🐩', n: 'poodle' },
  { c: '1f42c', e: '🐬', n: 'dolphin' },
  { c: '1f42d', e: '🐭', n: 'mouse face' },
  { c: '1f42e', e: '🐮', n: 'cow face' },
  { c: '1f430', e: '🐰', n: 'rabbit face' },
  { c: '1f431', e: '🐱', n: 'cat face' },
  { c: '1f433', e: '🐳', n: 'spouting whale' },
  { c: '1f436', e: '🐶', n: 'dog face' },
  { c: '1f438', e: '🐸', n: 'frog' },
  { c: '1f43b', e: '🐻', n: 'bear' },
  { c: '1f43c', e: '🐼', n: 'panda' },
  { c: '1f43e', e: '🐾', n: 'paw prints' },
  { c: '1f43f', e: '🐿', n: 'chipmunk' },
  { c: '1f440', e: '👀', n: 'eyes' },
  { c: '1f441', e: '👁', n: 'eye' },
  { c: '1f442', e: '👂', n: 'ear' },
  { c: '1f443', e: '👃', n: 'nose' },
  { c: '1f446', e: '👆', n: 'backhand index pointing up' },
  { c: '1f447', e: '👇', n: 'backhand index pointing down' },
  { c: '1f448', e: '👈', n: 'backhand index pointing left' },
  { c: '1f449', e: '👉', n: 'backhand index pointing right' },
  { c: '1f44a', e: '👊', n: 'oncoming fist' },
  { c: '1f44b', e: '👋', n: 'waving hand' },
  { c: '1f44c', e: '👌', n: 'OK hand' },
  { c: '1f44d', e: '👍', n: 'thumbs up' },
  { c: '1f44e', e: '👎', n: 'thumbs down' },
  { c: '1f44f', e: '👏', n: 'clapping hands' },
  { c: '1f450', e: '👐', n: 'open hands sign' },
  { c: '1f463', e: '👣', n: 'footprints' },
  { c: '1f47b', e: '👻', n: 'ghost' },
  { c: '1f47d', e: '👽', n: 'alien' },
  { c: '1f47e', e: '👾', n: 'alien monster' },
  { c: '1f47f', e: '👿', n: 'imp' },
  { c: '1f480', e: '💀', n: 'skull' },
  { c: '1f483', e: '💃', n: 'dancer' },
  { c: '1f485', e: '💅', n: 'nail polish' },
  { c: '1f48b', e: '💋', n: 'kiss mark' },
  { c: '1f48c', e: '💌', n: 'love letter' },
  { c: '1f48d', e: '💍', n: 'ring' },
  { c: '1f48e', e: '💎', n: 'gem stone' },
  { c: '1f490', e: '💐', n: 'bouquet' },
  { c: '1f493', e: '💓', n: 'beating heart' },
  { c: '1f494', e: '💔', n: 'broken heart' },
  { c: '1f495', e: '💕', n: 'two hearts' },
  { c: '1f496', e: '💖', n: 'sparkling heart' },
  { c: '1f497', e: '💗', n: 'growing heart' },
  { c: '1f498', e: '💘', n: 'heart with arrow' },
  { c: '1f499', e: '💙', n: 'blue heart' },
  { c: '1f49a', e: '💚', n: 'green heart' },
  { c: '1f49b', e: '💛', n: 'yellow heart' },
  { c: '1f49c', e: '💜', n: 'purple heart' },
  { c: '1f49d', e: '💝', n: 'heart with ribbon' },
  { c: '1f49e', e: '💞', n: 'revolving hearts' },
  { c: '1f49f', e: '💟', n: 'heart decoration' },
  { c: '1f4a1', e: '💡', n: 'light bulb' },
  { c: '1f4a2', e: '💢', n: 'anger symbol' },
  { c: '1f4a3', e: '💣', n: 'bomb' },
  { c: '1f4a4', e: '💤', n: 'zzz' },
  { c: '1f4a5', e: '💥', n: 'collision' },
  { c: '1f4a6', e: '💦', n: 'sweat droplets' },
  { c: '1f4a7', e: '💧', n: 'droplet' },
  { c: '1f4a9', e: '💩', n: 'pile of poo' },
  { c: '1f4aa', e: '💪', n: 'flexed biceps' },
  { c: '1f4ab', e: '💫', n: 'dizzy symbol' },
  { c: '1f4af', e: '💯', n: 'hundred points' },
  { c: '1f4b8', e: '💸', n: 'money with wings' },
  { c: '1f4bb', e: '💻', n: 'laptop' },
  { c: '1f4e7', e: '📧', n: 'e-mail' },
  { c: '1f4f1', e: '📱', n: 'mobile phone' },
  { c: '1f4f4', e: '📴', n: 'mobile phone off' },
  { c: '1f4f8', e: '📸', n: 'camera with flash' },
  { c: '1f50b', e: '🔋', n: 'battery' },
  { c: '1f511', e: '🔑', n: 'key' },
  { c: '1f512', e: '🔒', n: 'lock' },
  { c: '1f514', e: '🔔', n: 'bell' },
  { c: '1f525', e: '🔥', n: 'fire' },
  { c: '1f52e', e: '🔮', n: 'crystal ball' },
  { c: '1f54a', e: '🕊', n: 'dove of peace' },
  { c: '1f577', e: '🕷', n: 'spider' },
  { c: '1f590', e: '🖐️', n: 'hand with fingers splayed' },
  { c: '1f595', e: '🖕', n: 'reversed hand with middle finger extended' },
  { c: '1f596', e: '🖖', n: 'vulcan salute' },
  { c: '1f5a4', e: '🖤', n: 'black heart' },
  { c: '1f600', e: '😀', n: 'grinning face' },
  { c: '1f601', e: '😁', n: 'beaming face with smiling eyes' },
  { c: '1f602', e: '😂', n: 'face with tears of joy' },
  { c: '1f603', e: '😃', n: 'grinning face with big eyes' },
  { c: '1f604', e: '😄', n: 'grinning face with smiling eyes' },
  { c: '1f605', e: '😅', n: 'grinning face with sweat' },
  { c: '1f606', e: '😆', n: 'smiling face with open mouth and tightly-closed eyes' },
  { c: '1f607', e: '😇', n: 'smiling face with halo' },
  { c: '1f608', e: '😈', n: 'smiling face with horns' },
  { c: '1f609', e: '😉', n: 'winking face' },
  { c: '1f60a', e: '😊', n: 'smiling face with smiling eyes' },
  { c: '1f60b', e: '😋', n: 'face savoring food' },
  { c: '1f60c', e: '😌', n: 'relieved face' },
  { c: '1f60d', e: '😍', n: 'smiling face with heart-eyes' },
  { c: '1f60e', e: '😎', n: 'smiling face with sunglasses' },
  { c: '1f60f', e: '😏', n: 'smirking face' },
  { c: '1f610', e: '😐', n: 'neutral face' },
  { c: '1f611', e: '😑', n: 'expressionless face' },
  { c: '1f612', e: '😒', n: 'unamused face' },
  { c: '1f613', e: '😓', n: 'face with cold sweat' },
  { c: '1f614', e: '😔', n: 'pensive face' },
  { c: '1f615', e: '😕', n: 'confused face' },
  { c: '1f616', e: '😖', n: 'confounded face' },
  { c: '1f617', e: '😗', n: 'kissing face' },
  { c: '1f618', e: '😘', n: 'face blowing a kiss' },
  { c: '1f619', e: '😙', n: 'kissing face with smiling eyes' },
  { c: '1f61a', e: '😚', n: 'kissing face with closed eyes' },
  { c: '1f61b', e: '😛', n: 'face with tongue' },
  { c: '1f61c', e: '😜', n: 'winking face with tongue' },
  { c: '1f61d', e: '😝', n: 'squinting face with tongue' },
  { c: '1f61e', e: '😞', n: 'disappointed face' },
  { c: '1f61f', e: '😟', n: 'worried face' },
  { c: '1f620', e: '😠', n: 'angry face' },
  { c: '1f621', e: '😡', n: 'enraged face' },
  { c: '1f622', e: '😢', n: 'crying face' },
  { c: '1f623', e: '😣', n: 'persevering face' },
  { c: '1f624', e: '😤', n: 'face with look of triumph' },
  { c: '1f625', e: '😥', n: 'disappointed but relieved face' },
  { c: '1f626', e: '😦', n: 'frowning face with open mouth' },
  { c: '1f627', e: '😧', n: 'anguished face' },
  { c: '1f628', e: '😨', n: 'fearful face' },
  { c: '1f629', e: '😩', n: 'weary face' },
  { c: '1f62a', e: '😪', n: 'sleepy face' },
  { c: '1f62b', e: '😫', n: 'tired face' },
  { c: '1f62c', e: '😬', n: 'grimacing face' },
  { c: '1f62d', e: '😭', n: 'loudly crying face' },
  { c: '1f62e', e: '😮', n: 'face with open mouth' },
  { c: '1f62f', e: '😯', n: 'hushed face' },
  { c: '1f630', e: '😰', n: 'anxious face with sweat' },
  { c: '1f631', e: '😱', n: 'face screaming in fear' },
  { c: '1f632', e: '😲', n: 'astonished face' },
  { c: '1f633', e: '😳', n: 'flushed face' },
  { c: '1f634', e: '😴', n: 'sleeping face' },
  { c: '1f635', e: '😵', n: 'dizzy face' },
  { c: '1f636', e: '😶', n: 'face without mouth' },
  { c: '1f637', e: '😷', n: 'face with medical mask' },
  { c: '1f638', e: '😸', n: 'grinning cat face with smiling eyes' },
  { c: '1f639', e: '😹', n: 'cat face with tears of joy' },
  { c: '1f63a', e: '😺', n: 'smiling cat face with open mouth' },
  { c: '1f63b', e: '😻', n: 'smiling cat face with heart-shaped eyes' },
  { c: '1f63c', e: '😼', n: 'cat face with wry smile' },
  { c: '1f63d', e: '😽', n: 'kissing cat face with closed eyes' },
  { c: '1f63e', e: '😾', n: 'pouting cat face' },
  { c: '1f63f', e: '😿', n: 'crying cat face' },
  { c: '1f640', e: '🙀', n: 'weary cat face' },
  { c: '1f641', e: '🙁', n: 'slightly frowning face' },
  { c: '1f642', e: '🙂', n: 'slightly smiling face' },
  { c: '1f643', e: '🙃', n: 'upside-down face' },
  { c: '1f644', e: '🙄', n: 'face with rolling eyes' },
  { c: '1f648', e: '🙈', n: 'see-no-evil monkey' },
  { c: '1f649', e: '🙉', n: 'hear-no-evil monkey' },
  { c: '1f64a', e: '🙊', n: 'speak-no-evil monkey' },
  { c: '1f64c', e: '🙌', n: 'raising hands' },
  { c: '1f64f', e: '🙏', n: 'folded hands' },
  { c: '1f680', e: '🚀', n: 'rocket' },
  { c: '1f68c', e: '🚌', n: 'bus' },
  { c: '1f695', e: '🚕', n: 'taxi' },
  { c: '1f697', e: '🚗', n: 'automobile' },
  { c: '1f6a7', e: '🚧', n: 'construction sign' },
  { c: '1f6a8', e: '🚨', n: 'police cars revolving light' },
  { c: '1f6a9', e: '🚩', n: 'triangular flag on post' },
  { c: '1f6ae', e: '🚮', n: 'put litter in its place symbol' },
  { c: '1f6b2', e: '🚲', n: 'bicycle' },
  { c: '1f6ce', e: '🛎', n: 'bellhop bell' },
  { c: '1f6eb', e: '🛫', n: 'airplane departure' },
  { c: '1f6ec', e: '🛬', n: 'airplane arriving' },
  { c: '1f6f6', e: '🛶', n: 'canoe' },
  { c: '1f6f8', e: '🛸', n: 'flying saucer' },
  { c: '1f6f9', e: '🛹', n: 'skateboard' },
  { c: '1f6fc', e: '🛼', n: 'roller skate' },
  { c: '1f90c', e: '🤌', n: 'pinched fingers' },
  { c: '1f90d', e: '🤍', n: 'white heart' },
  { c: '1f90e', e: '🤎', n: 'brown heart' },
  { c: '1f90f', e: '🤏', n: 'pinching hand' },
  { c: '1f910', e: '🤐', n: 'zipper-mouth face' },
  { c: '1f911', e: '🤑', n: 'money-mouth face' },
  { c: '1f912', e: '🤒', n: 'face with thermometer' },
  { c: '1f913', e: '🤓', n: 'nerd face' },
  { c: '1f914', e: '🤔', n: 'thinking face' },
  { c: '1f915', e: '🤕', n: 'face with head-bandage' },
  { c: '1f916', e: '🤖', n: 'robot face' },
  { c: '1f917', e: '🤗', n: 'smiling face with open hands' },
  { c: '1f918', e: '🤘', n: 'sign of the horns' },
  { c: '1f919', e: '🤙', n: 'call me hand' },
  { c: '1f91a', e: '🤚', n: 'raised back of hand' },
  { c: '1f91b', e: '🤛', n: 'left-facing fist' },
  { c: '1f91c', e: '🤜', n: 'right-facing fist' },
  { c: '1f91d', e: '🤝', n: 'handshake' },
  { c: '1f91e', e: '🤞', n: 'crossed fingers' },
  { c: '1f91f', e: '🤟', n: 'love-you gesture' },
  { c: '1f920', e: '🤠', n: 'face with cowboy hat' },
  { c: '1f921', e: '🤡', n: 'clown face' },
  { c: '1f922', e: '🤢', n: 'nauseated face' },
  { c: '1f923', e: '🤣', n: 'rolling on the floor laughing' },
  { c: '1f924', e: '🤤', n: 'drooling face' },
  { c: '1f925', e: '🤥', n: 'lying face' },
  { c: '1f927', e: '🤧', n: 'sneezing face' },
  { c: '1f928', e: '🤨', n: 'face with raised eyebrow' },
  { c: '1f929', e: '🤩', n: 'star-struck' },
  { c: '1f92a', e: '🤪', n: 'zany face' },
  { c: '1f92b', e: '🤫', n: 'shushing face' },
  { c: '1f92c', e: '🤬', n: 'face with symbols on mouth' },
  { c: '1f92d', e: '🤭', n: 'face with hand over mouth' },
  { c: '1f92e', e: '🤮', n: 'face vomiting' },
  { c: '1f92f', e: '🤯', n: 'shocked face with exploding head' },
  { c: '1f932', e: '🤲', n: 'palms up together' },
  { c: '1f933', e: '🤳', n: 'selfie' },
  { c: '1f940', e: '🥀', n: 'wilted flower' },
  { c: '1f941', e: '🥁', n: 'drum with drumsticks' },
  { c: '1f942', e: '🥂', n: 'clinking glasses' },
  { c: '1f947', e: '🥇', n: '1st place medal' },
  { c: '1f948', e: '🥈', n: 'second place medal' },
  { c: '1f949', e: '🥉', n: 'third place medal' },
  { c: '1f94b', e: '🥋', n: 'martial arts uniform' },
  { c: '1f94d', e: '🥍', n: 'lacrosse stick and ball' },
  { c: '1f94e', e: '🥎', n: 'softball' },
  { c: '1f94f', e: '🥏', n: 'flying disc' },
  { c: '1f970', e: '🥰', n: 'smiling face with hearts' },
  { c: '1f971', e: '🥱', n: 'yawning face' },
  { c: '1f972', e: '🥲', n: 'smiling face with tear' },
  { c: '1f973', e: '🥳', n: 'face with party horn and party hat' },
  { c: '1f974', e: '🥴', n: 'face with uneven eyes and wavy mouth' },
  { c: '1f975', e: '🥵', n: 'overheated face' },
  { c: '1f976', e: '🥶', n: 'freezing face' },
  { c: '1f978', e: '🥸', n: 'disguised face' },
  { c: '1f979', e: '🥹', n: 'face holding back tears' },
  { c: '1f97a', e: '🥺', n: 'pleading face' },
  { c: '1f980', e: '🦀', n: 'crab' },
  { c: '1f982', e: '🦂', n: 'scorpion' },
  { c: '1f984', e: '🦄', n: 'unicorn face' },
  { c: '1f985', e: '🦅', n: 'eagle' },
  { c: '1f987', e: '🦇', n: 'bat' },
  { c: '1f988', e: '🦈', n: 'shark' },
  { c: '1f989', e: '🦉', n: 'owl' },
  { c: '1f98a', e: '🦊', n: 'fox' },
  { c: '1f98b', e: '🦋', n: 'butterfly' },
  { c: '1f98d', e: '🦍', n: 'gorilla' },
  { c: '1f98e', e: '🦎', n: 'lizard' },
  { c: '1f995', e: '🦕', n: 'sauropod' },
  { c: '1f996', e: '🦖', n: 't-rex' },
  { c: '1f998', e: '🦘', n: 'kangaroo' },
  { c: '1f99a', e: '🦚', n: 'peacock' },
  { c: '1f99e', e: '🦞', n: 'lobster' },
  { c: '1f99f', e: '🦟', n: 'mosquito' },
  { c: '1f9a0', e: '🦠', n: 'microbe' },
  { c: '1f9a6', e: '🦦', n: 'otter' },
  { c: '1f9a7', e: '🦧', n: 'orangutan' },
  { c: '1f9ad', e: '🦭', n: 'seal' },
  { c: '1f9ae', e: '🦮', n: 'guide dog' },
  { c: '1f9b5', e: '🦵', n: 'leg' },
  { c: '1f9b6', e: '🦶', n: 'foot' },
  { c: '1f9bb', e: '🦻', n: 'ear with hearing aid' },
  { c: '1f9be', e: '🦾', n: 'mechanical arm' },
  { c: '1f9bf', e: '🦿', n: 'mechanical leg' },
  { c: '1f9d0', e: '🧐', n: 'face with monocle' },
  { c: '1f9e1', e: '🧡', n: 'orange heart' },
  { c: '1fa70', e: '🩰', n: 'ballet shoes' },
  { c: '1fa75', e: '🩵', n: 'light blue heart' },
  { c: '1fa76', e: '🩶', n: 'grey heart' },
  { c: '1fa77', e: '🩷', n: 'pink heart' },
  { c: '1fa78', e: '🩸', n: 'drop of blood' },
  { c: '1fa81', e: '🪁', n: 'kite' },
  { c: '1fa83', e: '🪃', n: 'boomerang' },
  { c: '1fa84', e: '🪄', n: 'magic wand' },
  { c: '1fa85', e: '🪅', n: 'pinata' },
  { c: '1fa87', e: '🪇', n: 'maracas' },
  { c: '1fa89', e: '🪉', n: '🪉' },
  { c: '1fa8f', e: '🪏', n: '🪏' },
  { c: '1fa99', e: '🪙', n: 'coin' },
  { c: '1faa4', e: '🪤', n: 'mouse trap' },
  { c: '1faa9', e: '🪩', n: 'mirror ball' },
  { c: '1faab', e: '🪫', n: 'low battery' },
  { c: '1faad', e: '🪭', n: 'folding hand fan' },
  { c: '1fab0', e: '🪰', n: 'fly' },
  { c: '1fab1', e: '🪱', n: 'worm' },
  { c: '1fab3', e: '🪳', n: 'cockroach' },
  { c: '1fabc', e: '🪼', n: 'jellyfish' },
  { c: '1fabe', e: '🪾', n: '🪾' },
  { c: '1fabf', e: '🪿', n: 'goose' },
  { c: '1fac0', e: '🫀', n: 'anatomical heart' },
  { c: '1fac6', e: '🫆', n: '🫆' },
  { c: '1facf', e: '🫏', n: 'donkey' },
  { c: '1fad7', e: '🫗', n: 'pouring liquid' },
  { c: '1fadc', e: '🫜', n: '🫜' },
  { c: '1fadf', e: '🫟', n: '🫟' },
  { c: '1fae0', e: '🫠', n: 'melting face' },
  { c: '1fae1', e: '🫡', n: 'saluting face' },
  { c: '1fae2', e: '🫢', n: 'face with open eyes and hand over mouth' },
  { c: '1fae3', e: '🫣', n: 'face with peeking eye' },
  { c: '1fae4', e: '🫤', n: 'face with diagonal mouth' },
  { c: '1fae5', e: '🫥', n: 'dotted line face' },
  { c: '1fae6', e: '🫦', n: 'biting lip' },
  { c: '1fae7', e: '🫧', n: 'bubbles' },
  { c: '1fae8', e: '🫨', n: 'shaking face' },
  { c: '1fae9', e: '🫩', n: '🫩' },
  { c: '1faf0', e: '🫰', n: 'hand with index finger and thumb crossed' },
  { c: '1faf1', e: '🫱', n: 'rightwards hand' },
  { c: '1faf2', e: '🫲', n: 'leftwards hand' },
  { c: '1faf3', e: '🫳', n: 'palm down hand' },
  { c: '1faf4', e: '🫴', n: 'palm up hand' },
  { c: '1faf5', e: '🫵', n: 'index pointing at the viewer' },
  { c: '1faf6', e: '🫶', n: 'heart hands' },
  { c: '1faf7', e: '🫷', n: 'leftwards pushing hand' },
  { c: '1faf8', e: '🫸', n: 'rightwards pushing hand' },
  { c: '2602', e: '☂', n: 'umbrella' },
  { c: '2603', e: '☃', n: 'snowman' },
  { c: '2604', e: '☄', n: 'comet' },
  { c: '2615', e: '☕', n: 'hot beverage' },
  { c: '261d', e: '☝', n: 'white up pointing index' },
  { c: '2622', e: '☢', n: 'radioactive sign' },
  { c: '2623', e: '☣', n: 'biohazard sign' },
  { c: '262e', e: '☮', n: 'peace symbol' },
  { c: '262f', e: '☯', n: 'yin yang' },
  { c: '2639', e: '☹', n: 'white frowning face' },
  { c: '263a', e: '☺', n: 'white smiling face' },
  { c: '2648', e: '♈', n: 'aries' },
  { c: '2649', e: '♉', n: 'taurus' },
  { c: '264a', e: '♊', n: 'gemini' },
  { c: '264b', e: '♋', n: 'cancer' },
  { c: '264c', e: '♌', n: 'leo' },
  { c: '264d', e: '♍', n: 'virgo' },
  { c: '264e', e: '♎', n: 'libra' },
  { c: '264f', e: '♏', n: 'scorpius' },
  { c: '2650', e: '♐', n: 'sagittarius' },
  { c: '2651', e: '♑', n: 'capricorn' },
  { c: '2652', e: '♒', n: 'aquarius' },
  { c: '2653', e: '♓', n: 'pisces' },
  { c: '267e', e: '♾', n: 'permanent paper sign' },
  { c: '2696', e: '⚖', n: 'scales' },
  { c: '2699', e: '⚙', n: 'gear' },
  { c: '26a0', e: '⚠️', n: 'warning' },
  { c: '26a1', e: '⚡', n: 'high voltage sign' },
  { c: '26bd', e: '⚽', n: 'soccer ball' },
  { c: '26be', e: '⚾', n: 'baseball' },
  { c: '26c4', e: '⛄', n: 'snowman without snow' },
  { c: '26ce', e: '⛎', n: 'ophiuchus' },
  { c: '26f3', e: '⛳', n: 'flag in hole' },
  { c: '26f5', e: '⛵', n: 'sailboat' },
  { c: '26f8', e: '⛸', n: 'ice skate' },
  { c: '2705', e: '✅', n: 'check mark button' },
  { c: '270a', e: '✊', n: 'raised fist' },
  { c: '270b', e: '✋', n: 'raised hand' },
  { c: '270c', e: '✌️', n: 'victory hand' },
  { c: '270d', e: '✍', n: 'writing hand' },
  { c: '270f', e: '✏', n: 'pencil' },
  { c: '2728', e: '✨', n: 'sparkles' },
  { c: '2744', e: '❄', n: 'snowflake' },
  { c: '274c', e: '❌', n: 'cross mark' },
  { c: '2753', e: '❓', n: 'red question mark' },
  { c: '2757', e: '❗', n: 'red exclamation mark' },
  { c: '2763', e: '❣', n: 'heavy heart exclamation mark ornament' },
  { c: '2764', e: '❤️', n: 'red heart' },
  { c: '2764_200d_1f525', e: '❤️‍🔥', n: 'heart on fire' },
  { c: '2764_200d_1fa79', e: '❤️‍🩹', n: 'mending heart' },
  { c: '2795', e: '➕', n: 'heavy plus sign' },
  { c: '2b50', e: '⭐', n: 'star' },
];
