version: 2

registries:
  cgraph-dev-npm:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}

updates:
  - package-ecosystem: npm
    directory: /
    registries:
      - cgraph-dev-npm
    schedule:
      interval: daily
      time: '04:00'
      timezone: Europe/Bucharest
    open-pull-requests-limit: 5
    allow:
      - dependency-name: '@cgraph-dev/*'
    groups:
      cgraph-dev-packages:
        patterns:
          - '@cgraph-dev/*'
    commit-message:
      prefix: chore(packages)
      include: scope
