export { createApiClient } from './client';
export type { ApiClientConfig, ApiClient } from './client';

export {
  createNodesEndpoints,
  createCommissionEndpoints,
  CommissionStatusSchema,
  createBountyEndpoints,
  createCreatorEndpoints,
  createNotificationEndpoints,
  createFriendsEndpoints,
  createGroupsEndpoints,
  createForumsEndpoints,
  createSearchEndpoints,
  createSyncEndpoints,
  createInviteEndpoints,
  createSettingsEndpoints,
  createUploadEndpoints,
  createMessagingEndpoints,
  createBillingEndpoints,
  createAuthEndpoints,
  createProfileEndpoints,
  createCosmeticsEndpoints,
  createPresenceEndpoints,
  createReactionEndpoints,
  createE2EEEndpoints,
  createCallsEndpoints,
  createMediaEndpoints,
  createTranscriptionEndpoints,
  createCallQualityEndpoints,
} from './endpoints';

export type {
  // Commissions
  Commission,
  CommissionStatus,
  CommissionList,
  // Bounties
  Bounty,
  BountyEntry,
  BountyList,
  BountyEntryList,
  // Sync
  SyncPullResponse,
  SyncPushResponse,
  SearchFilters,
  GlobalSearchResponse,
  SearchSuggestion,
  SearchUser,
  SearchGroup,
  SearchMessage,
  SearchForum,
  SearchPost,
  RecentSearch,
  UploadResult,
  Message,
  Conversation,
  MessageList,
  ConversationList,
  SendMessageParams,
  FetchMessagesParams,
  GetConversationsParams,
  BillingStatus,
  PlanInfo,
  CheckoutSession,
  PortalSession,
  InvoiceRecord,
  UpdatePlanResponse,
  CancelSubscriptionResponse,
  Wallet,
  Transaction,
  Bundle,
  CheckoutResponse,
  GiftResult,
  // Creator analytics
  CreatorStatus,
  CreatorBalance,
  PayoutRequest,
  AnalyticsOverview,
  OnboardResponse,
  PremiumThread,
  CreatorTier,
  EarningsData,
  SubscriberAnalytics,
  ContentAnalyticsEnhanced,
  RevenueBreakdownData,
  SubscriberGrowthData,
  // Forums
  Forum,
  ForumVoteResult,
  Board,
  Post,
  PostPage,
  Comment,
  Poll,
  PollVoteResult,
  Thread,
  ThreadPost,
  ThreadPrefix,
  ForumMember,
  ForumSearchPage,
  LeaderboardPage,
  ForumSubscription,
  ForumAck,
  ForumCursorParams,
  ThreadListParams,
  PostFeedParams,
  MemberListParams,
  ForumSearchParams,
  // Auth
  LoginResult,
  RegisterResponse,
  RefreshResponse,
  TwoFactorResponse,
  OAuthProvidersResponse,
  OAuthResponse,
  ForgotPasswordResponse,
  ResetPasswordResponse,
  VerifyEmailResponse,
  WalletChallengeResponse,
  WalletAuthResponse,
  QrSessionResponse,
  TwoFactorStatus,
  TwoFactorSetup,
  BackupCodes,
  PhoneRequestResponse,
  PhoneVerifyResponse,
  PhoneCallFallbackResponse,
  CountriesResponse,
  Country,
  RegisterParams,
  WalletVerifyParams,
  // Profile
  FullUserProfile,
  PublicProfile,
  UpdateProfileParams,
  ReputationEntry,
  ReputationSummary,
  ReputationResponse,
  // Cosmetics
  CosmeticType,
  RarityTier,
  AnimationType,
  UnlockType,
  CosmeticItem,
  InventoryItem,
  InventoryResponse,
  ShopItem,
  ShopResponse,
  EquipResponse,
  PurchaseResponse,
  // Presence
  OnlineUser,
  PresenceResponse,
  UpdateStatusResult,
  GetOnlineUsersParams,
  // Reactions
  Reaction,
  ReactionSummary,
  // E2EE
  BootstrapStatus,
  KeyRegistrationResponse,
  PrekeyBundle,
  PrekeyCount,
  ReplenishKeysResponse,
  DeviceList,
  RemoveDeviceResponse,
  SafetyNumber,
  KeyVerifyResponse,
  KeyRevokeResponse,
  KeyBackupStoreResponse,
  KeyBackupGetResponse,
  CrossSignResponse,
  DeviceTrustChain,
  SyncPackageResponse,
  SyncPackagesList,
  OneTimePrekey,
  RegisterKeysParams,
  StoreKeyBackupParams,
  CrossSignParams,
  SyncKeysParams,
  // Calls
  CallInfo,
  CallHistory,
  MissedCallCount,
  MissedSeenResult,
  IceServersResult,
  GetCallHistoryParams,
  // Media
  MediaType,
  MediaItem,
  GalleryMeta,
  GalleryResponse,
  AvatarUploadResult,
  GetGalleryParams,
  // Transcription
  TranscriptionQueued,
  TranscriptionResultData,
  // Call Quality
  CallQualityReportResponseData,
} from './endpoints';

export { apiCall, extractData } from './schemas/api-result';
export type { ApiResult, ApiSuccess, ApiError } from './schemas/api-result';

export * from './schemas';
